/* Generated by gupnp-binding-tool */

#include <libgupnp/gupnp.h>

#ifndef GUPNP_GENERATED_CLIENT_BINDING_AVT
#define GUPNP_GENERATED_CLIENT_BINDING_AVT

G_BEGIN_DECLS

#ifndef __GUPNPASYNCDATA_TYPE__
#define __GUPNPASYNCDATA_TYPE__
typedef struct {GCallback cb; gpointer userdata; } GUPnPAsyncData;
#endif
static void
_free_cb_data (gpointer data, GClosure *closure)
{
  GUPnPAsyncData *cbdata = (GUPnPAsyncData *) data;
  g_slice_free1 (sizeof (*cbdata), cbdata);
}


/* action SetAVTransportURI */

static inline void
avt_set_av_transport_uri_action_get (GUPnPServiceAction *action,
                                     guint *in_instance_id,
                                     gchar **in_current_uri,
                                     gchar **in_current_uri_meta_data)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "CurrentURI", G_TYPE_STRING, in_current_uri,
                            "CurrentURIMetaData", G_TYPE_STRING, in_current_uri_meta_data,
                            NULL);
}

static inline gulong
avt_set_av_transport_uri_action_connect (GUPnPService *service,
                                         GCallback callback,
                                         gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetAVTransportURI",
                           callback,
                           userdata);
}


/* action SetNextAVTransportURI */

static inline void
avt_set_next_av_transport_uri_action_get (GUPnPServiceAction *action,
                                          guint *in_instance_id,
                                          gchar **in_next_uri,
                                          gchar **in_next_uri_meta_data)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "NextURI", G_TYPE_STRING, in_next_uri,
                            "NextURIMetaData", G_TYPE_STRING, in_next_uri_meta_data,
                            NULL);
}

static inline gulong
avt_set_next_av_transport_uri_action_connect (GUPnPService *service,
                                              GCallback callback,
                                              gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetNextAVTransportURI",
                           callback,
                           userdata);
}


/* action GetMediaInfo */

static inline void
avt_get_media_info_action_get (GUPnPServiceAction *action,
                               guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
avt_get_media_info_action_set (GUPnPServiceAction *action,
                               const guint out_nr_tracks,
                               const gchar *out_media_duration,
                               const gchar *out_current_uri,
                               const gchar *out_current_uri_meta_data,
                               const gchar *out_next_uri,
                               const gchar *out_next_uri_meta_data,
                               const gchar *out_play_medium,
                               const gchar *out_record_medium,
                               const gchar *out_write_status)
{
  gupnp_service_action_set (action,
                            "NrTracks", G_TYPE_UINT, out_nr_tracks,
                            "MediaDuration", G_TYPE_STRING, out_media_duration,
                            "CurrentURI", G_TYPE_STRING, out_current_uri,
                            "CurrentURIMetaData", G_TYPE_STRING, out_current_uri_meta_data,
                            "NextURI", G_TYPE_STRING, out_next_uri,
                            "NextURIMetaData", G_TYPE_STRING, out_next_uri_meta_data,
                            "PlayMedium", G_TYPE_STRING, out_play_medium,
                            "RecordMedium", G_TYPE_STRING, out_record_medium,
                            "WriteStatus", G_TYPE_STRING, out_write_status,
                            NULL);
}

static inline gulong
avt_get_media_info_action_connect (GUPnPService *service,
                                   GCallback callback,
                                   gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetMediaInfo",
                           callback,
                           userdata);
}


/* action GetTransportInfo */

static inline void
avt_get_transport_info_action_get (GUPnPServiceAction *action,
                                   guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
avt_get_transport_info_action_set (GUPnPServiceAction *action,
                                   const gchar *out_current_transport_state,
                                   const gchar *out_current_transport_status,
                                   const gchar *out_current_speed)
{
  gupnp_service_action_set (action,
                            "CurrentTransportState", G_TYPE_STRING, out_current_transport_state,
                            "CurrentTransportStatus", G_TYPE_STRING, out_current_transport_status,
                            "CurrentSpeed", G_TYPE_STRING, out_current_speed,
                            NULL);
}

static inline gulong
avt_get_transport_info_action_connect (GUPnPService *service,
                                       GCallback callback,
                                       gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetTransportInfo",
                           callback,
                           userdata);
}


/* action GetPositionInfo */

static inline void
avt_get_position_info_action_get (GUPnPServiceAction *action,
                                  guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
avt_get_position_info_action_set (GUPnPServiceAction *action,
                                  const guint out_track,
                                  const gchar *out_track_duration,
                                  const gchar *out_track_meta_data,
                                  const gchar *out_track_uri,
                                  const gchar *out_rel_time,
                                  const gchar *out_abs_time,
                                  const gint out_rel_count,
                                  const gint out_abs_count)
{
  gupnp_service_action_set (action,
                            "Track", G_TYPE_UINT, out_track,
                            "TrackDuration", G_TYPE_STRING, out_track_duration,
                            "TrackMetaData", G_TYPE_STRING, out_track_meta_data,
                            "TrackURI", G_TYPE_STRING, out_track_uri,
                            "RelTime", G_TYPE_STRING, out_rel_time,
                            "AbsTime", G_TYPE_STRING, out_abs_time,
                            "RelCount", G_TYPE_INT, out_rel_count,
                            "AbsCount", G_TYPE_INT, out_abs_count,
                            NULL);
}

static inline gulong
avt_get_position_info_action_connect (GUPnPService *service,
                                      GCallback callback,
                                      gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetPositionInfo",
                           callback,
                           userdata);
}


/* action GetDeviceCapabilities */

static inline void
avt_get_device_capabilities_action_get (GUPnPServiceAction *action,
                                        guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
avt_get_device_capabilities_action_set (GUPnPServiceAction *action,
                                        const gchar *out_play_media,
                                        const gchar *out_rec_media,
                                        const gchar *out_rec_quality_modes)
{
  gupnp_service_action_set (action,
                            "PlayMedia", G_TYPE_STRING, out_play_media,
                            "RecMedia", G_TYPE_STRING, out_rec_media,
                            "RecQualityModes", G_TYPE_STRING, out_rec_quality_modes,
                            NULL);
}

static inline gulong
avt_get_device_capabilities_action_connect (GUPnPService *service,
                                            GCallback callback,
                                            gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetDeviceCapabilities",
                           callback,
                           userdata);
}


/* action GetTransportSettings */

static inline void
avt_get_transport_settings_action_get (GUPnPServiceAction *action,
                                       guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
avt_get_transport_settings_action_set (GUPnPServiceAction *action,
                                       const gchar *out_play_mode,
                                       const gchar *out_rec_quality_mode)
{
  gupnp_service_action_set (action,
                            "PlayMode", G_TYPE_STRING, out_play_mode,
                            "RecQualityMode", G_TYPE_STRING, out_rec_quality_mode,
                            NULL);
}

static inline gulong
avt_get_transport_settings_action_connect (GUPnPService *service,
                                           GCallback callback,
                                           gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetTransportSettings",
                           callback,
                           userdata);
}


/* action Stop */

static inline void
avt_stop_action_get (GUPnPServiceAction *action,
                     guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline gulong
avt_stop_action_connect (GUPnPService *service,
                         GCallback callback,
                         gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::Stop",
                           callback,
                           userdata);
}


/* action Play */

static inline void
avt_play_action_get (GUPnPServiceAction *action,
                     guint *in_instance_id,
                     gchar **in_speed)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Speed", G_TYPE_STRING, in_speed,
                            NULL);
}

static inline gulong
avt_play_action_connect (GUPnPService *service,
                         GCallback callback,
                         gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::Play",
                           callback,
                           userdata);
}


/* action Pause */

static inline void
avt_pause_action_get (GUPnPServiceAction *action,
                      guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline gulong
avt_pause_action_connect (GUPnPService *service,
                          GCallback callback,
                          gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::Pause",
                           callback,
                           userdata);
}


/* action Seek */

static inline void
avt_seek_action_get (GUPnPServiceAction *action,
                     guint *in_instance_id,
                     gchar **in_unit,
                     gchar **in_target)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Unit", G_TYPE_STRING, in_unit,
                            "Target", G_TYPE_STRING, in_target,
                            NULL);
}

static inline gulong
avt_seek_action_connect (GUPnPService *service,
                         GCallback callback,
                         gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::Seek",
                           callback,
                           userdata);
}


/* action Next */

static inline void
avt_next_action_get (GUPnPServiceAction *action,
                     guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline gulong
avt_next_action_connect (GUPnPService *service,
                         GCallback callback,
                         gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::Next",
                           callback,
                           userdata);
}


/* action Previous */

static inline void
avt_previous_action_get (GUPnPServiceAction *action,
                         guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline gulong
avt_previous_action_connect (GUPnPService *service,
                             GCallback callback,
                             gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::Previous",
                           callback,
                           userdata);
}


/* state variable TransportState */

typedef gchar *(*avt_transport_state_query_callback) (GUPnPService *service,
                                                      gpointer userdata);

static void
_avt_transport_state_query_cb (GUPnPService *service,
                               gchar *variable,
                               GValue *value,
                               gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *transport_state;

  cbdata = (GUPnPAsyncData *) userdata;
  transport_state = ((avt_transport_state_query_callback)cbdata->cb) (service,
                                                                      cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, transport_state);
}

gulong
avt_transport_state_query_connect (GUPnPService *service,
                                   avt_transport_state_query_callback callback,
                                   gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::TransportState",
                                G_CALLBACK (_avt_transport_state_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable TransportStatus */

typedef gchar *(*avt_transport_status_query_callback) (GUPnPService *service,
                                                       gpointer userdata);

static void
_avt_transport_status_query_cb (GUPnPService *service,
                                gchar *variable,
                                GValue *value,
                                gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *transport_status;

  cbdata = (GUPnPAsyncData *) userdata;
  transport_status = ((avt_transport_status_query_callback)cbdata->cb) (service,
                                                                        cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, transport_status);
}

gulong
avt_transport_status_query_connect (GUPnPService *service,
                                    avt_transport_status_query_callback callback,
                                    gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::TransportStatus",
                                G_CALLBACK (_avt_transport_status_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable PlaybackStorageMedium */

typedef gchar *(*avt_playback_storage_medium_query_callback) (GUPnPService *service,
                                                              gpointer userdata);

static void
_avt_playback_storage_medium_query_cb (GUPnPService *service,
                                       gchar *variable,
                                       GValue *value,
                                       gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *playback_storage_medium;

  cbdata = (GUPnPAsyncData *) userdata;
  playback_storage_medium = ((avt_playback_storage_medium_query_callback)cbdata->cb) (service,
                                                                                      cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, playback_storage_medium);
}

gulong
avt_playback_storage_medium_query_connect (GUPnPService *service,
                                           avt_playback_storage_medium_query_callback callback,
                                           gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::PlaybackStorageMedium",
                                G_CALLBACK (_avt_playback_storage_medium_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable RecordStorageMedium */

typedef gchar *(*avt_record_storage_medium_query_callback) (GUPnPService *service,
                                                            gpointer userdata);

static void
_avt_record_storage_medium_query_cb (GUPnPService *service,
                                     gchar *variable,
                                     GValue *value,
                                     gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *record_storage_medium;

  cbdata = (GUPnPAsyncData *) userdata;
  record_storage_medium = ((avt_record_storage_medium_query_callback)cbdata->cb) (service,
                                                                                  cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, record_storage_medium);
}

gulong
avt_record_storage_medium_query_connect (GUPnPService *service,
                                         avt_record_storage_medium_query_callback callback,
                                         gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::RecordStorageMedium",
                                G_CALLBACK (_avt_record_storage_medium_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable PossiblePlaybackStorageMedia */

typedef gchar *(*avt_possible_playback_storage_media_query_callback) (GUPnPService *service,
                                                                      gpointer userdata);

static void
_avt_possible_playback_storage_media_query_cb (GUPnPService *service,
                                               gchar *variable,
                                               GValue *value,
                                               gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *possible_playback_storage_media;

  cbdata = (GUPnPAsyncData *) userdata;
  possible_playback_storage_media = ((avt_possible_playback_storage_media_query_callback)cbdata->cb) (service,
                                                                                                      cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, possible_playback_storage_media);
}

gulong
avt_possible_playback_storage_media_query_connect (GUPnPService *service,
                                                   avt_possible_playback_storage_media_query_callback callback,
                                                   gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::PossiblePlaybackStorageMedia",
                                G_CALLBACK (_avt_possible_playback_storage_media_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable PossibleRecordStorageMedia */

typedef gchar *(*avt_possible_record_storage_media_query_callback) (GUPnPService *service,
                                                                    gpointer userdata);

static void
_avt_possible_record_storage_media_query_cb (GUPnPService *service,
                                             gchar *variable,
                                             GValue *value,
                                             gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *possible_record_storage_media;

  cbdata = (GUPnPAsyncData *) userdata;
  possible_record_storage_media = ((avt_possible_record_storage_media_query_callback)cbdata->cb) (service,
                                                                                                  cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, possible_record_storage_media);
}

gulong
avt_possible_record_storage_media_query_connect (GUPnPService *service,
                                                 avt_possible_record_storage_media_query_callback callback,
                                                 gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::PossibleRecordStorageMedia",
                                G_CALLBACK (_avt_possible_record_storage_media_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable CurrentPlayMode */

typedef gchar *(*avt_current_play_mode_query_callback) (GUPnPService *service,
                                                        gpointer userdata);

static void
_avt_current_play_mode_query_cb (GUPnPService *service,
                                 gchar *variable,
                                 GValue *value,
                                 gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *current_play_mode;

  cbdata = (GUPnPAsyncData *) userdata;
  current_play_mode = ((avt_current_play_mode_query_callback)cbdata->cb) (service,
                                                                          cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, current_play_mode);
}

gulong
avt_current_play_mode_query_connect (GUPnPService *service,
                                     avt_current_play_mode_query_callback callback,
                                     gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::CurrentPlayMode",
                                G_CALLBACK (_avt_current_play_mode_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable TransportPlaySpeed */

typedef gchar *(*avt_transport_play_speed_query_callback) (GUPnPService *service,
                                                           gpointer userdata);

static void
_avt_transport_play_speed_query_cb (GUPnPService *service,
                                    gchar *variable,
                                    GValue *value,
                                    gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *transport_play_speed;

  cbdata = (GUPnPAsyncData *) userdata;
  transport_play_speed = ((avt_transport_play_speed_query_callback)cbdata->cb) (service,
                                                                                cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, transport_play_speed);
}

gulong
avt_transport_play_speed_query_connect (GUPnPService *service,
                                        avt_transport_play_speed_query_callback callback,
                                        gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::TransportPlaySpeed",
                                G_CALLBACK (_avt_transport_play_speed_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable RecordMediumWriteStatus */

typedef gchar *(*avt_record_medium_write_status_query_callback) (GUPnPService *service,
                                                                 gpointer userdata);

static void
_avt_record_medium_write_status_query_cb (GUPnPService *service,
                                          gchar *variable,
                                          GValue *value,
                                          gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *record_medium_write_status;

  cbdata = (GUPnPAsyncData *) userdata;
  record_medium_write_status = ((avt_record_medium_write_status_query_callback)cbdata->cb) (service,
                                                                                            cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, record_medium_write_status);
}

gulong
avt_record_medium_write_status_query_connect (GUPnPService *service,
                                              avt_record_medium_write_status_query_callback callback,
                                              gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::RecordMediumWriteStatus",
                                G_CALLBACK (_avt_record_medium_write_status_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable CurrentRecordQualityMode */

typedef gchar *(*avt_current_record_quality_mode_query_callback) (GUPnPService *service,
                                                                  gpointer userdata);

static void
_avt_current_record_quality_mode_query_cb (GUPnPService *service,
                                           gchar *variable,
                                           GValue *value,
                                           gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *current_record_quality_mode;

  cbdata = (GUPnPAsyncData *) userdata;
  current_record_quality_mode = ((avt_current_record_quality_mode_query_callback)cbdata->cb) (service,
                                                                                              cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, current_record_quality_mode);
}

gulong
avt_current_record_quality_mode_query_connect (GUPnPService *service,
                                               avt_current_record_quality_mode_query_callback callback,
                                               gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::CurrentRecordQualityMode",
                                G_CALLBACK (_avt_current_record_quality_mode_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable PossibleRecordQualityModes */

typedef gchar *(*avt_possible_record_quality_modes_query_callback) (GUPnPService *service,
                                                                    gpointer userdata);

static void
_avt_possible_record_quality_modes_query_cb (GUPnPService *service,
                                             gchar *variable,
                                             GValue *value,
                                             gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *possible_record_quality_modes;

  cbdata = (GUPnPAsyncData *) userdata;
  possible_record_quality_modes = ((avt_possible_record_quality_modes_query_callback)cbdata->cb) (service,
                                                                                                  cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, possible_record_quality_modes);
}

gulong
avt_possible_record_quality_modes_query_connect (GUPnPService *service,
                                                 avt_possible_record_quality_modes_query_callback callback,
                                                 gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::PossibleRecordQualityModes",
                                G_CALLBACK (_avt_possible_record_quality_modes_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable NumberOfTracks */

typedef guint (*avt_number_of_tracks_query_callback) (GUPnPService *service,
                                                      gpointer userdata);

static void
_avt_number_of_tracks_query_cb (GUPnPService *service,
                                gchar *variable,
                                GValue *value,
                                gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint number_of_tracks;

  cbdata = (GUPnPAsyncData *) userdata;
  number_of_tracks = ((avt_number_of_tracks_query_callback)cbdata->cb) (service,
                                                                        cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, number_of_tracks);
}

gulong
avt_number_of_tracks_query_connect (GUPnPService *service,
                                    avt_number_of_tracks_query_callback callback,
                                    gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::NumberOfTracks",
                                G_CALLBACK (_avt_number_of_tracks_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable CurrentTrack */

typedef guint (*avt_current_track_query_callback) (GUPnPService *service,
                                                   gpointer userdata);

static void
_avt_current_track_query_cb (GUPnPService *service,
                             gchar *variable,
                             GValue *value,
                             gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint current_track;

  cbdata = (GUPnPAsyncData *) userdata;
  current_track = ((avt_current_track_query_callback)cbdata->cb) (service,
                                                                  cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, current_track);
}

gulong
avt_current_track_query_connect (GUPnPService *service,
                                 avt_current_track_query_callback callback,
                                 gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::CurrentTrack",
                                G_CALLBACK (_avt_current_track_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable CurrentTrackDuration */

typedef gchar *(*avt_current_track_duration_query_callback) (GUPnPService *service,
                                                             gpointer userdata);

static void
_avt_current_track_duration_query_cb (GUPnPService *service,
                                      gchar *variable,
                                      GValue *value,
                                      gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *current_track_duration;

  cbdata = (GUPnPAsyncData *) userdata;
  current_track_duration = ((avt_current_track_duration_query_callback)cbdata->cb) (service,
                                                                                    cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, current_track_duration);
}

gulong
avt_current_track_duration_query_connect (GUPnPService *service,
                                          avt_current_track_duration_query_callback callback,
                                          gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::CurrentTrackDuration",
                                G_CALLBACK (_avt_current_track_duration_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable CurrentMediaDuration */

typedef gchar *(*avt_current_media_duration_query_callback) (GUPnPService *service,
                                                             gpointer userdata);

static void
_avt_current_media_duration_query_cb (GUPnPService *service,
                                      gchar *variable,
                                      GValue *value,
                                      gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *current_media_duration;

  cbdata = (GUPnPAsyncData *) userdata;
  current_media_duration = ((avt_current_media_duration_query_callback)cbdata->cb) (service,
                                                                                    cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, current_media_duration);
}

gulong
avt_current_media_duration_query_connect (GUPnPService *service,
                                          avt_current_media_duration_query_callback callback,
                                          gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::CurrentMediaDuration",
                                G_CALLBACK (_avt_current_media_duration_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable CurrentTrackMetaData */

typedef gchar *(*avt_current_track_meta_data_query_callback) (GUPnPService *service,
                                                              gpointer userdata);

static void
_avt_current_track_meta_data_query_cb (GUPnPService *service,
                                       gchar *variable,
                                       GValue *value,
                                       gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *current_track_meta_data;

  cbdata = (GUPnPAsyncData *) userdata;
  current_track_meta_data = ((avt_current_track_meta_data_query_callback)cbdata->cb) (service,
                                                                                      cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, current_track_meta_data);
}

gulong
avt_current_track_meta_data_query_connect (GUPnPService *service,
                                           avt_current_track_meta_data_query_callback callback,
                                           gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::CurrentTrackMetaData",
                                G_CALLBACK (_avt_current_track_meta_data_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable CurrentTrackURI */

typedef gchar *(*avt_current_track_uri_query_callback) (GUPnPService *service,
                                                        gpointer userdata);

static void
_avt_current_track_uri_query_cb (GUPnPService *service,
                                 gchar *variable,
                                 GValue *value,
                                 gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *current_track_uri;

  cbdata = (GUPnPAsyncData *) userdata;
  current_track_uri = ((avt_current_track_uri_query_callback)cbdata->cb) (service,
                                                                          cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, current_track_uri);
}

gulong
avt_current_track_uri_query_connect (GUPnPService *service,
                                     avt_current_track_uri_query_callback callback,
                                     gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::CurrentTrackURI",
                                G_CALLBACK (_avt_current_track_uri_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable AVTransportURI */

typedef gchar *(*avt_av_transport_uri_query_callback) (GUPnPService *service,
                                                       gpointer userdata);

static void
_avt_av_transport_uri_query_cb (GUPnPService *service,
                                gchar *variable,
                                GValue *value,
                                gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *av_transport_uri;

  cbdata = (GUPnPAsyncData *) userdata;
  av_transport_uri = ((avt_av_transport_uri_query_callback)cbdata->cb) (service,
                                                                        cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, av_transport_uri);
}

gulong
avt_av_transport_uri_query_connect (GUPnPService *service,
                                    avt_av_transport_uri_query_callback callback,
                                    gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::AVTransportURI",
                                G_CALLBACK (_avt_av_transport_uri_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable AVTransportURIMetaData */

typedef gchar *(*avt_av_transport_uri_meta_data_query_callback) (GUPnPService *service,
                                                                 gpointer userdata);

static void
_avt_av_transport_uri_meta_data_query_cb (GUPnPService *service,
                                          gchar *variable,
                                          GValue *value,
                                          gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *av_transport_uri_meta_data;

  cbdata = (GUPnPAsyncData *) userdata;
  av_transport_uri_meta_data = ((avt_av_transport_uri_meta_data_query_callback)cbdata->cb) (service,
                                                                                            cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, av_transport_uri_meta_data);
}

gulong
avt_av_transport_uri_meta_data_query_connect (GUPnPService *service,
                                              avt_av_transport_uri_meta_data_query_callback callback,
                                              gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::AVTransportURIMetaData",
                                G_CALLBACK (_avt_av_transport_uri_meta_data_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable NextAVTransportURI */

typedef gchar *(*avt_next_av_transport_uri_query_callback) (GUPnPService *service,
                                                            gpointer userdata);

static void
_avt_next_av_transport_uri_query_cb (GUPnPService *service,
                                     gchar *variable,
                                     GValue *value,
                                     gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *next_av_transport_uri;

  cbdata = (GUPnPAsyncData *) userdata;
  next_av_transport_uri = ((avt_next_av_transport_uri_query_callback)cbdata->cb) (service,
                                                                                  cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, next_av_transport_uri);
}

gulong
avt_next_av_transport_uri_query_connect (GUPnPService *service,
                                         avt_next_av_transport_uri_query_callback callback,
                                         gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::NextAVTransportURI",
                                G_CALLBACK (_avt_next_av_transport_uri_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable NextAVTransportURIMetaData */

typedef gchar *(*avt_next_av_transport_uri_meta_data_query_callback) (GUPnPService *service,
                                                                      gpointer userdata);

static void
_avt_next_av_transport_uri_meta_data_query_cb (GUPnPService *service,
                                               gchar *variable,
                                               GValue *value,
                                               gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *next_av_transport_uri_meta_data;

  cbdata = (GUPnPAsyncData *) userdata;
  next_av_transport_uri_meta_data = ((avt_next_av_transport_uri_meta_data_query_callback)cbdata->cb) (service,
                                                                                                      cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, next_av_transport_uri_meta_data);
}

gulong
avt_next_av_transport_uri_meta_data_query_connect (GUPnPService *service,
                                                   avt_next_av_transport_uri_meta_data_query_callback callback,
                                                   gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::NextAVTransportURIMetaData",
                                G_CALLBACK (_avt_next_av_transport_uri_meta_data_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable RelativeTimePosition */

typedef gchar *(*avt_relative_time_position_query_callback) (GUPnPService *service,
                                                             gpointer userdata);

static void
_avt_relative_time_position_query_cb (GUPnPService *service,
                                      gchar *variable,
                                      GValue *value,
                                      gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *relative_time_position;

  cbdata = (GUPnPAsyncData *) userdata;
  relative_time_position = ((avt_relative_time_position_query_callback)cbdata->cb) (service,
                                                                                    cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, relative_time_position);
}

gulong
avt_relative_time_position_query_connect (GUPnPService *service,
                                          avt_relative_time_position_query_callback callback,
                                          gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::RelativeTimePosition",
                                G_CALLBACK (_avt_relative_time_position_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable AbsoluteTimePosition */

typedef gchar *(*avt_absolute_time_position_query_callback) (GUPnPService *service,
                                                             gpointer userdata);

static void
_avt_absolute_time_position_query_cb (GUPnPService *service,
                                      gchar *variable,
                                      GValue *value,
                                      gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *absolute_time_position;

  cbdata = (GUPnPAsyncData *) userdata;
  absolute_time_position = ((avt_absolute_time_position_query_callback)cbdata->cb) (service,
                                                                                    cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, absolute_time_position);
}

gulong
avt_absolute_time_position_query_connect (GUPnPService *service,
                                          avt_absolute_time_position_query_callback callback,
                                          gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::AbsoluteTimePosition",
                                G_CALLBACK (_avt_absolute_time_position_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable RelativeCounterPosition */

typedef gint (*avt_relative_counter_position_query_callback) (GUPnPService *service,
                                                              gpointer userdata);

static void
_avt_relative_counter_position_query_cb (GUPnPService *service,
                                         gchar *variable,
                                         GValue *value,
                                         gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gint relative_counter_position;

  cbdata = (GUPnPAsyncData *) userdata;
  relative_counter_position = ((avt_relative_counter_position_query_callback)cbdata->cb) (service,
                                                                                          cbdata->userdata);
  g_value_init (value, G_TYPE_INT);
  g_value_set_int (value, relative_counter_position);
}

gulong
avt_relative_counter_position_query_connect (GUPnPService *service,
                                             avt_relative_counter_position_query_callback callback,
                                             gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::RelativeCounterPosition",
                                G_CALLBACK (_avt_relative_counter_position_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable AbsoluteCounterPosition */

typedef gint (*avt_absolute_counter_position_query_callback) (GUPnPService *service,
                                                              gpointer userdata);

static void
_avt_absolute_counter_position_query_cb (GUPnPService *service,
                                         gchar *variable,
                                         GValue *value,
                                         gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gint absolute_counter_position;

  cbdata = (GUPnPAsyncData *) userdata;
  absolute_counter_position = ((avt_absolute_counter_position_query_callback)cbdata->cb) (service,
                                                                                          cbdata->userdata);
  g_value_init (value, G_TYPE_INT);
  g_value_set_int (value, absolute_counter_position);
}

gulong
avt_absolute_counter_position_query_connect (GUPnPService *service,
                                             avt_absolute_counter_position_query_callback callback,
                                             gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::AbsoluteCounterPosition",
                                G_CALLBACK (_avt_absolute_counter_position_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable CurrentTransportActions */

typedef gchar *(*avt_current_transport_actions_query_callback) (GUPnPService *service,
                                                                gpointer userdata);

static void
_avt_current_transport_actions_query_cb (GUPnPService *service,
                                         gchar *variable,
                                         GValue *value,
                                         gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *current_transport_actions;

  cbdata = (GUPnPAsyncData *) userdata;
  current_transport_actions = ((avt_current_transport_actions_query_callback)cbdata->cb) (service,
                                                                                          cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, current_transport_actions);
}

gulong
avt_current_transport_actions_query_connect (GUPnPService *service,
                                             avt_current_transport_actions_query_callback callback,
                                             gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::CurrentTransportActions",
                                G_CALLBACK (_avt_current_transport_actions_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable LastChange */

typedef gchar *(*avt_last_change_query_callback) (GUPnPService *service,
                                                  gpointer userdata);

static void
_avt_last_change_query_cb (GUPnPService *service,
                           gchar *variable,
                           GValue *value,
                           gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *last_change;

  cbdata = (GUPnPAsyncData *) userdata;
  last_change = ((avt_last_change_query_callback)cbdata->cb) (service,
                                                              cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, last_change);
}

gulong
avt_last_change_query_connect (GUPnPService *service,
                               avt_last_change_query_callback callback,
                               gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::LastChange",
                                G_CALLBACK (_avt_last_change_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}

void
avt_last_change_variable_notify (GUPnPService *service,
                                 const gchar *last_change)
{
  gupnp_service_notify (service,
                        "LastChange", G_TYPE_STRING, last_change,
                        NULL);
}


G_END_DECLS

#endif /* GUPNP_GENERATED_CLIENT_BINDING_AVT */
