/* Generated by gupnp-binding-tool */

#include <libgupnp/gupnp.h>

#ifndef GUPNP_GENERATED_CLIENT_BINDING_RC
#define GUPNP_GENERATED_CLIENT_BINDING_RC

G_BEGIN_DECLS

#ifndef __GUPNPASYNCDATA_TYPE__
#define __GUPNPASYNCDATA_TYPE__
typedef struct {GCallback cb; gpointer userdata; } GUPnPAsyncData;
#endif
static void
_free_cb_data (gpointer data, GClosure *closure)
{
  GUPnPAsyncData *cbdata = (GUPnPAsyncData *) data;
  g_slice_free1 (sizeof (*cbdata), cbdata);
}


/* action ListPresets */

static inline void
rc_list_presets_action_get (GUPnPServiceAction *action,
                            guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
rc_list_presets_action_set (GUPnPServiceAction *action,
                            const gchar *out_current_preset_name_list)
{
  gupnp_service_action_set (action,
                            "CurrentPresetNameList", G_TYPE_STRING, out_current_preset_name_list,
                            NULL);
}

static inline gulong
rc_list_presets_action_connect (GUPnPService *service,
                                GCallback callback,
                                gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::ListPresets",
                           callback,
                           userdata);
}


/* action SelectPreset */

static inline void
rc_select_preset_action_get (GUPnPServiceAction *action,
                             guint *in_instance_id,
                             gchar **in_preset_name)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "PresetName", G_TYPE_STRING, in_preset_name,
                            NULL);
}

static inline gulong
rc_select_preset_action_connect (GUPnPService *service,
                                 GCallback callback,
                                 gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SelectPreset",
                           callback,
                           userdata);
}


/* action GetVolume */

static inline void
rc_get_volume_action_get (GUPnPServiceAction *action,
                          guint *in_instance_id,
                          gchar **in_channel)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            NULL);
}

static inline void
rc_get_volume_action_set (GUPnPServiceAction *action,
                          const guint out_current_volume)
{
  gupnp_service_action_set (action,
                            "CurrentVolume", G_TYPE_UINT, out_current_volume,
                            NULL);
}

static inline gulong
rc_get_volume_action_connect (GUPnPService *service,
                              GCallback callback,
                              gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetVolume",
                           callback,
                           userdata);
}


/* action SetVolume */

static inline void
rc_set_volume_action_get (GUPnPServiceAction *action,
                          guint *in_instance_id,
                          gchar **in_channel,
                          guint *in_desired_volume)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            "DesiredVolume", G_TYPE_UINT, in_desired_volume,
                            NULL);
}

static inline gulong
rc_set_volume_action_connect (GUPnPService *service,
                              GCallback callback,
                              gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetVolume",
                           callback,
                           userdata);
}


/* state variable PresetNameList */

typedef gchar *(*rc_preset_name_list_query_callback) (GUPnPService *service,
                                                      gpointer userdata);

static void
_rc_preset_name_list_query_cb (GUPnPService *service,
                               gchar *variable,
                               GValue *value,
                               gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *preset_name_list;

  cbdata = (GUPnPAsyncData *) userdata;
  preset_name_list = ((rc_preset_name_list_query_callback)cbdata->cb) (service,
                                                                       cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, preset_name_list);
}

gulong
rc_preset_name_list_query_connect (GUPnPService *service,
                                   rc_preset_name_list_query_callback callback,
                                   gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::PresetNameList",
                                G_CALLBACK (_rc_preset_name_list_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable LastChange */

typedef gchar *(*rc_last_change_query_callback) (GUPnPService *service,
                                                 gpointer userdata);

static void
_rc_last_change_query_cb (GUPnPService *service,
                          gchar *variable,
                          GValue *value,
                          gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *last_change;

  cbdata = (GUPnPAsyncData *) userdata;
  last_change = ((rc_last_change_query_callback)cbdata->cb) (service,
                                                             cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, last_change);
}

gulong
rc_last_change_query_connect (GUPnPService *service,
                              rc_last_change_query_callback callback,
                              gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::LastChange",
                                G_CALLBACK (_rc_last_change_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}

void
rc_last_change_variable_notify (GUPnPService *service,
                                const gchar *last_change)
{
  gupnp_service_notify (service,
                        "LastChange", G_TYPE_STRING, last_change,
                        NULL);
}


/* state variable Volume */

typedef guint (*rc_volume_query_callback) (GUPnPService *service,
                                           gpointer userdata);

static void
_rc_volume_query_cb (GUPnPService *service,
                     gchar *variable,
                     GValue *value,
                     gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint volume;

  cbdata = (GUPnPAsyncData *) userdata;
  volume = ((rc_volume_query_callback)cbdata->cb) (service,
                                                   cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, volume);
}

gulong
rc_volume_query_connect (GUPnPService *service,
                         rc_volume_query_callback callback,
                         gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::Volume",
                                G_CALLBACK (_rc_volume_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable VolumeDB */

typedef gint (*rc_volume_db_query_callback) (GUPnPService *service,
                                             gpointer userdata);

static void
_rc_volume_db_query_cb (GUPnPService *service,
                        gchar *variable,
                        GValue *value,
                        gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gint volume_db;

  cbdata = (GUPnPAsyncData *) userdata;
  volume_db = ((rc_volume_db_query_callback)cbdata->cb) (service,
                                                         cbdata->userdata);
  g_value_init (value, G_TYPE_INT);
  g_value_set_int (value, volume_db);
}

gulong
rc_volume_db_query_connect (GUPnPService *service,
                            rc_volume_db_query_callback callback,
                            gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::VolumeDB",
                                G_CALLBACK (_rc_volume_db_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


G_END_DECLS

#endif /* GUPNP_GENERATED_CLIENT_BINDING_RC */
